version: '3.8'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080" 
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UnicornMagicDB;User Id=SA;Password=YourStrongPassword!;TrustServerCertificate=True
    depends_on:
      - sqlserver 
    restart: always 

  # Service pour SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=YourStrongPassword! 
                                       
    ports:
      - "1433:1433" 
    volumes:
      - sqlserver_data:/var/opt/mssql 
    restart: always 

volumes:
  sqlserver_data: 
    