// <auto-generated />
using System;
using EvalCedric.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvalCedric.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250611124635_UpdateMigrationAfterTests")]
    partial class UpdateMigrationAfterTests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvalCedric.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Leur corne pure peut réfracter la lumière lunaire en énergie curative.",
                            Name = "Corne de Cristal"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Leur crinière scintille avec la lumière d'étoiles lointaines. Ce sont de grands sages.",
                            Name = "Crinière d'Étoiles"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Leur robe est tachetée comme le soleil à travers les feuilles. Protecteurs des bois anciens.",
                            Name = "Gardien de la Forêt"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vivent sur les côtes et peuvent galoper sur l'eau. Leur robe a la couleur de l'écume.",
                            Name = "Écume de Mer"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Insaisissables et mystérieux, ils voyagent à travers les ombres.",
                            Name = "Sauteur d'Ombre"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Leur robe est d'obsidienne et leur crinière crépite comme de la lave. Ils canalisent l'énergie géothermique.",
                            Name = "Volcanique"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Leur pelage ondoie avec les couleurs célestes. Gardiens des ciels nocturnes du nord.",
                            Name = "Aurore Boréale"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Leur robe a la couleur du sable doré. Ils invoquent des mirages pour dérouter les voyageurs.",
                            Name = "Murmure des Sables"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Robustes, leur peau ressemble à du granit. Gardiens des trésors de la terre.",
                            Name = "Cœur de Montagne"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Presque éthérés, leur corps devient translucide à la pleine lune.",
                            Name = "Spectre Lunaire"
                        });
                });

            modelBuilder.Entity("Unicorn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MagicalPowers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.ToTable("Unicorns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreedId = 1,
                            Color = "Blanc perle",
                            DateOfBirth = new DateTime(1524, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sa corne luit d'une douce lumière apaisante.",
                            Diet = "Rosée du matin et fleurs de lune",
                            Habitat = "Clairières éclairées par la lune",
                            ImageUrl = "https://placehold.co/600x400/EAEAEA/333?text=Luminara",
                            MagicalPowers = "Guérison par la lumière et purification",
                            Name = "Luminara",
                            Origin = "Née d'un éclat de lune."
                        },
                        new
                        {
                            Id = 2,
                            BreedId = 1,
                            Color = "Ivoire et or",
                            DateOfBirth = new DateTime(1680, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sa corne capture l'énergie du soleil.",
                            Diet = "Nectar de tournesol",
                            Habitat = "Plateaux ensoleillés",
                            ImageUrl = "https://placehold.co/600x400/FFF8DC/333?text=Solarius",
                            MagicalPowers = "Rayons de lumière et chaleur bienfaisante",
                            Name = "Solarius",
                            Origin = "Incarnation d'un rayon de soleil."
                        },
                        new
                        {
                            Id = 3,
                            BreedId = 2,
                            Color = "Bleu nuit constellé",
                            DateOfBirth = new DateTime(877, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "De nouvelles constellations naissent de sa crinière.",
                            Diet = "Poussière de comète",
                            Habitat = "Sommets des montagnes",
                            ImageUrl = "https://placehold.co/600x400/000080/FFF?text=Céleste",
                            MagicalPowers = "Navigation stellaire et prophéties",
                            Name = "Céleste",
                            Origin = "Tissée à partir d'une nébuleuse."
                        },
                        new
                        {
                            Id = 4,
                            BreedId = 2,
                            Color = "Argent et saphir",
                            DateOfBirth = new DateTime(345, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Guide les voyageurs égarés.",
                            Diet = "Échos du Big Bang",
                            Habitat = "Observatoires anciens",
                            ImageUrl = "https://placehold.co/600x400/708090/FFF?text=Orion",
                            MagicalPowers = "Création de portails cosmiques",
                            Name = "Orion",
                            Origin = "Gardien d'une étoile déchue."
                        },
                        new
                        {
                            Id = 5,
                            BreedId = 3,
                            Color = "Vert mousse et or",
                            DateOfBirth = new DateTime(1250, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sa robe change avec les saisons.",
                            Diet = "Sève d'arbres anciens",
                            Habitat = "Forêts primordiales",
                            ImageUrl = "https://placehold.co/600x400/228B22/FFF?text=Veridian",
                            MagicalPowers = "Communication avec la faune et la flore",
                            Name = "Veridian",
                            Origin = "Esprit d'une forêt millénaire."
                        },
                        new
                        {
                            Id = 6,
                            BreedId = 3,
                            Color = "Écorce de bouleau",
                            DateOfBirth = new DateTime(1100, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Murmure les secrets des arbres.",
                            Diet = "Feuilles de chêne argenté",
                            Habitat = "Bosquets sacrés",
                            ImageUrl = "https://placehold.co/600x400/D2B48C/333?text=Sylva",
                            MagicalPowers = "Camouflage et guérison par les plantes",
                            Name = "Sylva",
                            Origin = "Née de la première graine."
                        },
                        new
                        {
                            Id = 7,
                            BreedId = 4,
                            Color = "Turquoise et blanc",
                            DateOfBirth = new DateTime(1801, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Laisse une traînée de perles irisées.",
                            Diet = "Plancton bioluminescent",
                            Habitat = "Récifs coralliens cachés",
                            ImageUrl = "https://placehold.co/600x400/40E0D0/333?text=Aquaria",
                            MagicalPowers = "Contrôle des courants",
                            Name = "Aquaria",
                            Origin = "Née du baiser de la lune sur l'océan."
                        },
                        new
                        {
                            Id = 8,
                            BreedId = 4,
                            Color = "Bleu océan profond",
                            DateOfBirth = new DateTime(1754, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Son galop sur l'eau annonce la marée haute.",
                            Diet = "Sel enchanté",
                            Habitat = "Grottes sous-marines",
                            ImageUrl = "https://placehold.co/600x400/0000CD/FFF?text=Marinus",
                            MagicalPowers = "Respiration aquatique et chant des sirènes",
                            Name = "Marinus",
                            Origin = "Gardien d'une cité engloutie."
                        },
                        new
                        {
                            Id = 9,
                            BreedId = 5,
                            Color = "Gris charbon",
                            DateOfBirth = new DateTime(999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "N'apparaît que lors de la nouvelle lune.",
                            Diet = "Silence et secrets",
                            Habitat = "Ruines oubliées",
                            ImageUrl = "https://placehold.co/600x400/2F4F4F/FFF?text=Noctis",
                            MagicalPowers = "Voyage dans les ombres et illusions",
                            Name = "Noctis",
                            Origin = "Tissé à partir de la première nuit."
                        },
                        new
                        {
                            Id = 10,
                            BreedId = 5,
                            Color = "Noir de jais",
                            DateOfBirth = new DateTime(666, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Son passage refroidit l'air ambiant.",
                            Diet = "Peur et doutes",
                            Habitat = "Carrefours des mondes",
                            ImageUrl = "https://placehold.co/600x400/000000/FFF?text=Umbra",
                            MagicalPowers = "Invisibilité et manipulation des rêves",
                            Name = "Umbra",
                            Origin = "Fragment d'éclipse."
                        },
                        new
                        {
                            Id = 11,
                            BreedId = 6,
                            Color = "Noir obsidienne",
                            DateOfBirth = new DateTime(432, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sa corne est un conduit de magma purifié.",
                            Diet = "Soufre et minéraux rares",
                            Habitat = "Caldeiras de volcans",
                            ImageUrl = "https://placehold.co/600x400/1C0000/FF4500?text=Ignis",
                            MagicalPowers = "Pyromancie et terraformation",
                            Name = "Ignis",
                            Origin = "Né du cœur en fusion de la terre."
                        },
                        new
                        {
                            Id = 12,
                            BreedId = 6,
                            Color = "Rouge et noir",
                            DateOfBirth = new DateTime(121, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sa crinière est une rivière de lave.",
                            Diet = "Roches en fusion",
                            Habitat = "Chambres magmatiques",
                            ImageUrl = "https://placehold.co/600x400/8B0000/FFD700?text=Magma",
                            MagicalPowers = "Endurance au feu et forge d'artefacts",
                            Name = "Magma",
                            Origin = "Gardien du noyau terrestre."
                        },
                        new
                        {
                            Id = 13,
                            BreedId = 7,
                            Color = "Multicolore et changeant",
                            DateOfBirth = new DateTime(1905, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Peint le ciel nocturne de son galop.",
                            Diet = "Cristaux de glace et vent solaire",
                            Habitat = "Toundra arctique",
                            ImageUrl = "https://placehold.co/600x400/8A2BE2/FFF?text=Aurora",
                            MagicalPowers = "Manipulation de la lumière et du froid",
                            Name = "Aurora",
                            Origin = "Esprit du ciel polaire."
                        },
                        new
                        {
                            Id = 14,
                            BreedId = 7,
                            Color = "Vert et rose pastel",
                            DateOfBirth = new DateTime(1859, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Son chant ressemble au craquement du champ magnétique terrestre.",
                            Diet = "Lumière des étoiles polaires",
                            Habitat = "Fjords gelés",
                            ImageUrl = "https://placehold.co/600x400/98FB98/FF69B4?text=Borealis",
                            MagicalPowers = "Hypnose visuelle et bouclier d'énergie",
                            Name = "Borealis",
                            Origin = "Reflet terrestre d'une galaxie lointaine."
                        },
                        new
                        {
                            Id = 15,
                            BreedId = 8,
                            Color = "Sable doré",
                            DateOfBirth = new DateTime(753, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Court plus vite que le vent du désert.",
                            Diet = "Chaleur du soleil et cactus en fleurs",
                            Habitat = "Dunes infinies",
                            ImageUrl = "https://placehold.co/600x400/F4A460/333?text=Sirocco",
                            MagicalPowers = "Création de tempêtes de sable et de mirages",
                            Name = "Sirocco",
                            Origin = "Né d'une tempête de sable millénaire."
                        },
                        new
                        {
                            Id = 16,
                            BreedId = 8,
                            Color = "Beige et turquoise",
                            DateOfBirth = new DateTime(1337, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trouve de l'eau là où il n'y en a pas.",
                            Diet = "Dattes et eau pure",
                            Habitat = "Oasis cachées",
                            ImageUrl = "https://placehold.co/600x400/F5DEB3/40E0D0?text=Oasis",
                            MagicalPowers = "Divination de l'eau et purification",
                            Name = "Oasis",
                            Origin = "Gardienne de la dernière oasis primordiale."
                        },
                        new
                        {
                            Id = 17,
                            BreedId = 9,
                            Color = "Gris tacheté de quartz",
                            DateOfBirth = new DateTime(200, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aussi solide et immuable que la montagne.",
                            Diet = "Gemmes et métaux bruts",
                            Habitat = "Cavernes de cristal",
                            ImageUrl = "https://placehold.co/600x400/696969/EEE?text=Granit",
                            MagicalPowers = "Force surhumaine et géomancie",
                            Name = "Granit",
                            Origin = "Cœur vivant d'une montagne."
                        },
                        new
                        {
                            Id = 18,
                            BreedId = 9,
                            Color = "Argent brillant",
                            DateOfBirth = new DateTime(580, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sa robe brille comme du métal poli.",
                            Diet = "Or et platine",
                            Habitat = "Veines de métaux précieux",
                            ImageUrl = "https://placehold.co/600x400/C0C0C0/333?text=Mithril",
                            MagicalPowers = "Invulnérabilité et détection des trésors",
                            Name = "Mithril",
                            Origin = "Forgé par des nains anciens."
                        },
                        new
                        {
                            Id = 19,
                            BreedId = 10,
                            Color = "Translucide et argenté",
                            DateOfBirth = new DateTime(1485, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Traverse les murs les nuits de pleine lune.",
                            Diet = "Lumière de lune et émotions résiduelles",
                            Habitat = "Cimetières anciens et plans astraux",
                            ImageUrl = "https://placehold.co/600x400/F5F5F5/333?text=Phasma",
                            MagicalPowers = "Intangibilité et communication avec les esprits",
                            Name = "Phasma",
                            Origin = "Écho d'un rêve."
                        },
                        new
                        {
                            Id = 20,
                            BreedId = 10,
                            Color = "Blanc laiteux",
                            DateOfBirth = new DateTime(1969, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "La plus proche de la lune elle-même.",
                            Diet = "Vide spatial",
                            Habitat = "Sur la lune",
                            ImageUrl = "https://placehold.co/600x400/FFFFFF/333?text=Luna",
                            MagicalPowers = "Contrôle de la gravité et voyage astral",
                            Name = "Luna",
                            Origin = "Née sur la face cachée de la lune."
                        });
                });

            modelBuilder.Entity("Unicorn", b =>
                {
                    b.HasOne("EvalCedric.Models.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");
                });
#pragma warning restore 612, 618
        }
    }
}
